# Generated by Django 4.1.6 on 2023-02-16 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Request_Info', '0006_remove_requestinfo_completetime'),
        ('User_AgentInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CompleteTime', models.TextField(null=True)),
                ('FinalPay', models.IntegerField(default=0, null=True)),
                ('ReservationNum', models.IntegerField(null=True)),
                ('AgentUserSNSKey', models.ForeignKey(db_column='SNSKey', max_length=45, on_delete=django.db.models.deletion.CASCADE, related_name='AgentUserInfo', to='User_AgentInfo.agentinfo')),
                ('RequestInfoID', models.ForeignKey(db_column='RequestInfoID', on_delete=django.db.models.deletion.CASCADE, related_name='RequestInfo', to='Request_Info.requestinfo')),
            ],
        ),
    ]
