# Generated by Django 4.1.6 on 2023-02-16 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Info', '0006_remove_requestinfo_completetime'),
        ('Contract_Info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractinfo',
            name='ContractProgress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractinfo',
            name='RequestInfoID',
            field=models.ForeignKey(db_column='RequestInfoID', on_delete=django.db.models.deletion.CASCADE, related_name='RequestInfo', to='Request_Info.requestinfo', unique=True),
        ),
    ]
