# Generated by Django 4.1.6 on 2023-02-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contract_Info', '0002_contractinfo_contractprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractinfo',
            name='PickedTime',
            field=models.TextField(null=True),
        ),
    ]
