# Generated by Django 4.1.6 on 2023-03-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contract_Info', '0003_contractinfo_pickedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractinfo',
            name='AgentUserSNSKey',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contractinfo',
            name='ContractProgress',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='contractinfo',
            name='PickedTime',
            field=models.DateTimeField(null=True),
        ),
    ]
