# Generated by Django 4.1.6 on 2023-03-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contract_Info', '0004_alter_contractinfo_agentusersnskey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractinfo',
            name='a',
            field=models.TextField(null=True),
        ),
    ]
