# Generated by Django 4.1.6 on 2023-03-08 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contract_Info', '0005_contractinfo_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractinfo',
            name='a',
        ),
    ]
