# Generated by Django 4.1.6 on 2023-03-13 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Info', '0003_rename_snskey_id_userinfo_snskey'),
        ('User_MyCar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycar',
            name='a',
        ),
        migrations.AlterField(
            model_name='mycar',
            name='SNSKey',
            field=models.ForeignKey(db_column='SNSKey', max_length=45, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myCarInfo', to='User_Info.userinfo'),
        ),
        migrations.AlterField(
            model_name='mycar',
            name='VehicleRegistrationCertificateURL',
            field=models.TextField(null=True),
        ),
    ]
