# Generated by Django 4.1.6 on 2023-02-13 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Info', '0001_initial'),
        ('Request_Info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinfo',
            name='SNSKey',
            field=models.ForeignKey(db_column='SNSKey', max_length=45, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RequestInfo', to='User_Info.userinfo'),
        ),
    ]
