# Generated by Django 4.1.6 on 2023-02-14 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Info', '0003_rename_snskey_requestinfo_snskey_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestinfo',
            old_name='SNSKey_id',
            new_name='SNSKey',
        ),
    ]
