# Generated by Django 4.1.6 on 2023-02-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Info', '0004_rename_snskey_id_requestinfo_snskey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinfo',
            name='MyCarID',
            field=models.IntegerField(),
        ),
    ]
