# Generated by Django 4.1.6 on 2023-02-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Info', '0006_remove_requestinfo_completetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinfo',
            name='CompleteTime',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='requestinfo',
            name='Garage',
            field=models.TextField(null=True),
        ),
    ]
