# Generated by Django 4.1.6 on 2023-02-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_Info', '0010_requestinfo_pickuplat_requestinfo_pickuplng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinfo',
            name='PickupLat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='requestinfo',
            name='PickupLng',
            field=models.FloatField(),
        ),
    ]
