# Generated by Django 4.1.6 on 2023-02-13 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SNSKey', models.CharField(max_length=45)),
                ('LicenseURL', models.TextField()),
                ('isPermitted', models.BooleanField(default=False)),
            ],
        ),
    ]
