# Generated by Django 4.1.6 on 2023-02-16 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Info', '0003_rename_snskey_id_userinfo_snskey'),
        ('User_AgentInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinfo',
            name='SNSKey',
            field=models.ForeignKey(db_column='SNSKey', max_length=45, on_delete=django.db.models.deletion.CASCADE, related_name='AgentInfo', to='User_Info.userinfo'),
        ),
    ]
