# Generated by Django 4.1.6 on 2023-02-16 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Info', '0003_rename_snskey_id_userinfo_snskey'),
        ('User_AgentInfo', '0003_alter_agentinfo_snskey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinfo',
            name='SNSKey',
            field=models.ForeignKey(db_column='SNSKey', max_length=45, on_delete=django.db.models.deletion.CASCADE, related_name='AgentUserInfo', to='User_Info.userinfo', unique=True),
        ),
    ]
