# Generated by Django 4.1.6 on 2023-03-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_AgentInfo', '0004_alter_agentinfo_snskey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentinfo',
            name='LicenseURL',
            field=models.TextField(null=True),
        ),
    ]
