# Generated by Django 4.1.6 on 2023-02-16 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contract_Info', '0003_contractinfo_pickedtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField(null=True)),
                ('Date', models.TextField()),
                ('StarRating', models.IntegerField()),
                ('WriteType', models.IntegerField()),
                ('ContractPostNum', models.ForeignKey(db_column='PostNum', on_delete=django.db.models.deletion.CASCADE, related_name='ContractInfo', to='Contract_Info.contractinfo')),
            ],
        ),
    ]
