# Generated by Django 4.1.6 on 2023-02-14 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='SNSKey',
            new_name='SNSKey_id',
        ),
    ]
