# Generated by Django 4.1.6 on 2023-02-14 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Info', '0002_rename_snskey_userinfo_snskey_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='SNSKey_id',
            new_name='SNSKey',
        ),
    ]
